name: Deploy to Debian Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read path to private key
        id: path
        run: echo "::set-output name=path::$(cat path)"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.185.229.220.231 }}"
          username: ${{ secrets.jannalmr }}
          key: ${{ steps.path.outputs.path }}
          agent: yes
          script: |
            cd /var/www/refletdegenie.shop

            # Check if the repository directory already exists
            if [ -d "RefletDeGenie" ]; then
              # If yes, perform a git pull to update the repository
              cd RefletDeGenie
              git pull origin main
            else
              # If not, clone the repository from GitHub
              git clone git@github.com:lamrij/RefletDeGenie.git
            fi
